name = "Optim"
author = "darksaid98"
version = "v1.14.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ec069b531a46301eca6b7ee803778c9d7431c1aabb1639361dac87c90c9fbbe7"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"

[options]
acceptable-game-versions = ["1.21"]
