name = "Optim"
author = "darksaid98"
version = "v1.13.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "50e14d7a897f5b97ec0006bcbd2bb7654070825571a9e59ff026bee8f1cb039b"

[versions]
fabric = "0.18.6"
minecraft = "1.21.11"

[options]
acceptable-game-versions = ["1.21"]
