name = "Optim"
author = "darksaid98"
version = "v1.13.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2cef58b38de1b0b55b8e6dc7ca59825beee93542d2cd1a18a925ff963b65f767"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"

[options]
acceptable-game-versions = ["1.21"]
